# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: shogo82148/actions-github-app-token@v1
        id: generateToken
        with: 
          app-id: 1688372

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env: 
          GH_TOKEN: ${{ steps.generateToken.outputs.token }}
        run: |
          gh auth status
          gh api /user
          gh api /octocat
